const models={Apple:['A1278','A1286','A1297','A1369','A1370','A1398','A1425','A1465','A1466','A1502','A1503','A1706','A1707','A1708','A1989','A1990','A2141','A2179','A2251','A2337','A2442','A2485','Other / Enter Model Manually'],Dell:['Latitude E5450','Latitude E5470','Latitude E5570','Latitude 5480','Latitude 5490','Latitude 7490','Latitude 7400','Latitude 7410','Latitude 5420','Latitude 5520','Latitude 7420','Latitude 7430','Inspiron 15 3000','Inspiron 15 5000','XPS 13','XPS 15','Precision 3540','Precision 5560','Other / Enter Model Manually'],HP:['ProBook 440 G3','ProBook 440 G5','ProBook 440 G6','ProBook 440 G7','ProBook 440 G8','EliteBook 840 G3','840 G5','840 G6','840 G7','840 G8','EliteBook 850 G5','ZBook 14 G2','ZBook Firefly 14 G8','Pavilion 15','Envy 13','Other / Enter Model Manually'],Lenovo:['ThinkPad T440p','T450','T460','T470','T480','T490','T14 Gen 1','T14 Gen 2','L440','L460','L470','L480','X240','X250','X260','X270','X280','IdeaPad 3','IdeaPad 5','Other / Enter Model Manually'],ASUS:['VivoBook 14','VivoBook 15','VivoBook S15','ZenBook 13','ZenBook 14','ROG Strix G15','TUF Gaming F15','ExpertBook B1','Other / Enter Model Manually'],Acer:['Aspire 3','Aspire 5','Aspire 7','Swift 3','Swift 5','TravelMate P2','Extensa 15','Nitro 5','Other / Enter Model Manually'],MSI:['Modern 14','Modern 15','Prestige 14','Prestige 15','GF63 Thin','Katana 15','Other / Enter Model Manually']};
const problems=['Not turning on','Screen / Display problem','Battery problem','Keyboard problem','Charging problem','SSD / HDD problem','RAM problem','Overheating','Windows / Software problem','Motherboard problem','Water / Liquid damage','Other'];
function fillModels(){let b=document.getElementById('brand').value.replace(' ','');let list=models[b]||models.Dell;document.getElementById('modelList').innerHTML=list.map(x=>`<div onclick="document.getElementById('model').value='${x.replaceAll("'","\'")}'">${x}</div>`).join('')}document.getElementById('brand').onchange=fillModels;fillModels();
function manualModel(){document.getElementById('model').value='';document.getElementById('model').focus()}
function openFlow(type){const modal=document.getElementById('modal'),flow=document.getElementById('flow');modal.style.display='flex'; if(type==='repair')stepBrand(flow);else if(type==='sell')stepSimple(flow,'Sell Your Laptop','Condition / details');else if(type==='upgrade')stepSimple(flow,'Laptop & CPU Upgrade','Upgrade required');else if(type==='adapter')stepSimple(flow,'Adapters & Chargers','Brand / wattage');else stepSimple(flow,'Buy Laptops','Preferred brand / model')}
function closeFlow(){document.getElementById('modal').style.display='none'}
function stepBrand(el){el.innerHTML='<h2 class="flow-title">Book a Repair</h2><div class="flow-grid">'+Object.keys(models).map(b=>`<button class="flow-btn" onclick="stepModel('${b}')">${b}</button>`).join('')+'</div>'}
function stepModel(b){let el=document.getElementById('flow');el.innerHTML=`<h2 class="flow-title">${b} Model</h2><div class="flow-grid">${models[b].map(m=>`<button class="flow-btn" onclick="stepProblem('${b}','${m.replaceAll("'","\'")}')">${m}</button>`).join('')}</div><button class="back" onclick="stepBrand(document.getElementById('flow'))">← Back</button>`}
function stepProblem(b,m){let el=document.getElementById('flow');el.innerHTML=`<h2 class="flow-title">${b} • ${m}</h2><div class="flow-grid">${problems.map(p=>`<button class="flow-btn" onclick="stepCustomer('${b}','${m.replaceAll("'","\'")}','${p.replaceAll("'","\'")}')">${p}</button>`).join('')}</div>`}
function stepCustomer(b,m,p){document.getElementById('flow').innerHTML=`<h2 class="flow-title">Customer Details</h2><p><b>${b} ${m}</b><br>${p}</p><div class="form"><input id="n" placeholder="Your name"><input id="ph" placeholder="Phone number"><textarea id="note" placeholder="Additional details"></textarea><button onclick="sendWA('${b}','${m.replaceAll("'","\'")}','${p.replaceAll("'","\'")}')">Send Request on WhatsApp</button></div>`}
function stepSimple(el,title,placeholder){el.innerHTML=`<h2 class="flow-title">${title}</h2><div class="form"><input id="n" placeholder="Your name"><input id="ph" placeholder="Phone number"><textarea id="note" placeholder="${placeholder}"></textarea><button onclick="sendWA('${title}','','')">Send Request on WhatsApp</button></div>`}
function sendWA(a,b,c){let n=document.getElementById('n').value||'Customer',ph=document.getElementById('ph').value||'',note=document.getElementById('note').value||'';let msg=`LapXpert Pro Request%0AName: ${encodeURIComponent(n)}%0APhone: ${encodeURIComponent(ph)}%0AService: ${encodeURIComponent(a)}%0AModel: ${encodeURIComponent(b)}%0AProblem/Details: ${encodeURIComponent(c+' '+note)}`;location.href='https://wa.me/919845885250?text='+msg}
